### ISSUE TITLE
Websocket connection closes

### ISSUE THREAD

**Issue by guikessa** [rampatra/jbot#115]
In my simulation, when i drop connection in my server and established after feel seconds, JBOT give me this error all the time.
"Error pinging Slack. Slack bot may go offline when not active. Exception:
java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed"

**Comment by rampatra** [comment]
Yes, this is because JBot sends a ping-pong message to slack every few seconds. Read this: https://github.com/rampatra/jbot/issues/103#issuecomment-397816857 for more info.

**Comment by guikessa** [comment]
I know about this ping-pong.I mean even when back he keeps saying he's offline. This is normal?

**Comment by rampatra** [comment]
Okay you mean after your connection resumes, your jbot starts responding to messages but on slack it shows "offline"?

**Comment by guikessa** [comment]
It doesn't respond messages after connection resumes. (sorry about my bad english)

**Comment by rampatra** [comment]
Okay from all the info, this is what I think. 
- When you break the connection b/w the bot and slack then the socket connection closes after some time
- Now, after the websocket connection is closed, the rtm url from slack will no more be valid
- You have to request a new rtm url from slack to connect to (i.e, you have to call `startRTMAndWebSocketConnection()` again)

Maybe I can add this as a new feature which would check for internet connectivity periodically and re-connect to slack.

**Comment by guikessa** [comment]
I tried to call the method startRTMAndWebSocketConnection() but the ping pong continues to respond that it is offline. it is as if the attribute is not in the new value. If you repair the Ping class it is built with the old websocket and the ping is done with it.

**Comment by rampatra** [comment]
Yes, I saw the code and it seems the old ping task will still be running along with a new ping task (with the new socket url). I have to actually kill the older ping task. I will modify and raise a PR. Thanks for reporting. 

Having said that, I still do not understand why your bot isn't responding even after you call `startRTMAndWebSocketConnection()` method.

**Comment by nixgadget** [comment]
@rampatra any progress/update on this issue ?

**Comment by katonica** [comment]
@rampatra Perhaps this issue is already fixed by https://github.com/rampatra/jbot/pull/138 ? Incorporating this code into my Slack bot seemed to fix our issues going offline. We had the same symptoms described above. Perhaps https://github.com/rampatra/jbot/pull/138 could be reviewed and incorporated into the code?

**Comment by gaurav517** [comment]
we still see that error. We see following intermittently.. every few mintues or so and then bot goes offline. Can you please suggest something. 
Thanks.
```
java.lang.IllegalStateException: The WebSocket session [0] has been closed and no method (apart from close()) may be called on a closed session
	at org.apache.tomcat.websocket.WsSession.checkState(WsSession.java:786)
	at org.apache.tomcat.websocket.WsSession.getBasicRemote(WsSession.java:432)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:203)
	at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:101)
	at me.ramswaroop.jbot.core.slack.Bot$PingTask.run(Bot.java:368)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gaurav517** [comment]
Also logs from 6 seconds before:
```
Starting WebSocketConnectionManager
Connecting to WebSocket at wss://cerberus-xxxx.lb.slack-msgs.com/websocket/abcd
Successfully connected
```
So 6 seconds before websocket was created, what is closing these sockets? And if sockets are being closed, then why is it not recreating them? Shouldn't be network.. because we have another bot using a javascript framework and that does not have this issue.

**Comment by rampatra** [comment]
@gaurav517 which JBot version are you using?

**Comment by gaurav517** [comment]
oh.. sorry.. I see now, the latest is `4.1.2-rc.2`with the fix.. I am using `4.1.2-rc.1`. will update and test.

**Comment by theimo1221** [comment]
Even with rc.2 I got that error: 

> .slack.Bot        : Error pinging Slack. Slack bot may go offline when not activ
e. Exception:

java.lang.IllegalStateException: Message will not be sent because the WebSocket
session has been closed

**Comment by trebusz** [comment]
Me too.

**Comment by Jsesan** [comment]
Hi im using the rc.2 but still getting the same error
